name: Bug Report
description: Report a bug in the app
title: "[Bug]: "
labels: ["bug"]

body:
  - type: checkboxes
    id: existing_issue
    attributes:
      label: "Is there an existing issue for this?"
      options:
        - label: "I have searched the existing issues"
          required: true
      
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: Which platform are you using?
      options:
        - iOS
        - Android
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please attach screenshots or videos if possible
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What should have happened?

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or videos
      description: Drag screenshots here
